export const PRODUCTS = [
  {
    _id: 'p1',
    name: 'Arogya Mantra Hair Oil',
    price: 249,
    category: 'hair',
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?w=600&q=80',
    description: 'Traditional Ayurvedic hair oil with bhringraj, amla, and brahmi. Reduces hairfall, nourishes the scalp, and promotes strong, lustrous growth.',
    benefits: ['Reduces hair fall', 'Nourishes scalp', 'Promotes growth'],
    variants: [
      { size: '100 ml', price: 249 },
      { size: '200 ml', price: 449 },
      { size: '500 ml', price: 999 },
    ],
  },
  {
    _id: 'p2',
    name: 'Abhyanga Tel',
    price: 249,
    category: 'body',
    badge: 'Signature',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80',
    description: 'Classical Panchakarma massage oil. Deeply relaxes muscles, moves toxins toward the gut for elimination, and calms the Vata dosha.',
    benefits: ['Detoxifies body', 'Calms Vata', 'Deep muscle relief'],
    variants: [
      { size: '100 ml', price: 249 },
      { size: '200 ml', price: 449 },
      { size: '500 ml', price: 999 },
    ],
  },
  {
    _id: 'p3',
    name: 'Shekekai Hair Shampoo',
    price: 125,
    category: 'hair',
    badge: null,
    image: 'https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=80',
    description: 'Natural reetha and shekekai-based cleanser. Gently cleanses without stripping natural oils. Sulphate-free and traditionally formulated.',
    benefits: ['Sulphate-free', 'Scalp-friendly', 'Natural herbs'],
    variants: [
      { size: '100 ml', price: 125 },
      { size: '200 ml', price: 220 },
    ],
  },
  {
    _id: 'p9',
    name: 'Anti-Dandruff Shampoo',
    price: 150,
    category: 'hair',
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    description: 'Ayurvedic anti-dandruff formula with neem, tulsi, and tea tree extracts. Eliminates dandruff at the root while keeping hair clean, soft, and healthy.',
    benefits: ['Removes dandruff', 'Neem & tulsi blend', 'Scalp treatment'],
    variants: [
      { size: '100 ml', price: 150 },
      { size: '200 ml', price: 270 },
    ],
  },
  {
    _id: 'p4',
    name: 'Arogya Mantra Ubtan',
    price: 75,
    category: 'skin',
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80',
    description: 'Herbal face and body ubtan with turmeric, sandalwood and rose. Gently exfoliates, brightens complexion and brings out your natural glow.',
    benefits: ['Brightens skin', 'Exfoliates gently', 'Natural glow'],
    variants: [
      { size: '50 gm', price: 75 },
      { size: '100 gm', price: 130 },
      { size: '200 gm', price: 240 },
    ],
  },
  {
    _id: 'p7',
    name: 'Natural Ayurvedic Soap',
    price: 120,
    category: 'skin',
    badge: null,
    image: 'https://images.unsplash.com/photo-1604085572504-a392ddf0d86a?w=600&q=80',
    description: '100% handcrafted Ayurvedic soap with neem, turmeric and coconut. No harsh chemicals, no parabens. Leaves skin clean, soft and nourished.',
    benefits: ['Chemical-free', 'Neem & turmeric', 'Skin nourishing'],
    variants: [
      { size: '75 gm', price: 120 },
      { size: '150 gm (Pack of 2)', price: 220 },
    ],
  },
  {
    _id: 'p5',
    name: 'Shahi Snan Bath Blend',
    price: 75,
    category: 'body',
    badge: null,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    description: 'A royal Ayurvedic bathing blend inspired by ancient palace rituals. Cleanses, softens and rejuvenates your skin from head to toe.',
    benefits: ['Softens skin', 'Royal ritual', 'Full body care'],
    variants: [
      { size: '100 gm', price: 75 },
      { size: '200 gm', price: 130 },
    ],
  },
  {
    _id: 'p10',
    name: 'Ayurvedic Hair Colour',
    price: 199,
    category: 'hair',
    badge: 'Doctor Formulated',
    image: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&q=80',
    description: 'Chemical-free hair colour with henna, indigo, amla, and Brahmi. Covers grey naturally while conditioning hair and promoting scalp health.',
    benefits: ['100% chemical-free', 'Covers greys', 'Conditions hair'],
    variants: [
      { size: '100 gm', price: 199 },
      { size: '200 gm', price: 360 },
    ],
  },
  {
    _id: 'p6',
    name: 'Murabba (Amla)',
    price: 250,
    category: 'wellness',
    badge: 'Doctor Prepared',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
    description: 'Doctor-prepared Amla Murabba, rich in Vitamin C and antioxidants. Excellent for immunity, digestion, and overall vitality. No preservatives.',
    benefits: ['Boosts immunity', 'Aids digestion', 'Rich in Vitamin C'],
    variants: [
      { size: '250 gm', price: 250 },
      { size: '500 gm', price: 470 },
    ],
  },
  {
    _id: 'p8',
    name: 'Chyawan Prash',
    price: 300,
    category: 'wellness',
    badge: 'Doctor Formulated',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80',
    description: 'Vrushali Maisekar\'s own formulation — a classic immunity tonic with 40+ Ayurvedic herbs. Strengthens immunity, improves digestion, and boosts energy.',
    benefits: ['40+ herbs', 'Builds immunity', 'Daily vitality'],
    variants: [
      { size: '250 gm', price: 300 },
      { size: '500 gm', price: 550 },
    ],
  },
]

export const SERVICES = [
  {
    id: 's1',
    title: 'Panchabhoutik Chikitsa',
    icon: 'five-elements',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=80',
    short: 'Five-element Ayurvedic treatment — pioneered by Late Vaidya A.V. Datar Shastri.',
    description: 'Treats through the five elements — Earth, Water, Fire, Air & Space — with minimum medicines. Agni (digestive fire) is central to every treatment protocol. Includes Prakriti assessment, Naad Pariksha, and root-cause treatment.',
    conditions: ['IBS & Acidity', 'Colitis', 'Piles & Fissure', 'PCOD', 'Infertility', 'Psoriasis', 'Eczema', 'Liver Disorders'],
  },
  {
    id: 's2',
    title: 'Yoga Therapy',
    icon: 'lotus',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    short: 'YCB Level 6 certified — India\'s highest yoga qualification under Ministry of AYUSH.',
    description: 'Special batches for PCOD, menopause, face yoga, and weight management. "Yoga Samatvam Uchyate" — treating body, mind and soul as a whole. Each session is therapeutic, not merely fitness.',
    conditions: ['PCOD', 'Menopause', 'Face Yoga', 'Weight Loss', 'Stress', 'Anxiety'],
  },
  {
    id: 's3',
    title: 'Panchakarma',
    icon: 'water-drop',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
    short: 'Complete Ayurvedic detox — Shirodhara, Abhyanga, Vaman, Basti & more.',
    description: 'Abhyanga (medicated oil massage), Shirodhara, Sarvanga Dhara, Vaman, Virechan, Basti, Nasya, and Rakta Mokshan — each carefully prescribed for your specific condition.',
    conditions: ['Shirodhara', 'Abhyanga', 'Nasya', 'Basti', 'Vaman', 'Virechan', 'Swedan', 'Rakta Mokshan'],
  },
  {
    id: 's4',
    title: 'Skinergy — Soundarya Mantra',
    icon: 'skin',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    short: 'Advanced Ayurvedic cosmetology with latest clinical equipment.',
    description: 'Detailed skin analysis, pinpoint diagnosis and a holistic treatment plan. Combines Ayurvedic formulations with modern cosmetology tools. Lifestyle-integrated treatment for long-term skin health and beauty.',
    conditions: ['Pimples', 'Pigmentation', 'Dark Circles', 'Skin Sagging', 'Dandruff', 'Scars', 'Hair Loss'],
  },
  {
    id: 's5',
    title: 'Hair Regain Clinic',
    icon: 'leaf',
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80',
    short: 'Hair loss treatment + premium wigs for men, women & cancer patients.',
    description: '10+ years of expertise in hair wigs and patches. Male/female pattern baldness, alopecia, dandruff treatment. Natural-look wigs — painless, no surgery, no medicines, pocket-friendly. Chemotherapy patients served with compassion.',
    conditions: ['Hair Loss', 'Alopecia Areata', 'Male Baldness', 'Chemotherapy Wigs', 'Hair Extensions', 'Patches'],
  },
  {
    id: 's6',
    title: "Women's & Digestive Health",
    icon: 'om',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80',
    short: 'Root-cause Ayurvedic treatment for complex women\'s health conditions.',
    description: 'Personalised protocols for every individual, integrating diet, lifestyle, herbs and yoga. Addressing the root, not just the symptom. Hundreds of success cases in PCOD, infertility, and menopause.',
    conditions: ['PCOD', 'Infertility', 'Irregular Menses', 'Colitis', 'Piles', 'Liver Disorders'],
  },
]

export const REVIEWS = [
  {
    id: 'r1',
    name: 'Priya Kulkarni',
    avatar: 'P',
    color: 'from-crimson to-gold',
    platform: 'Google',
    condition: 'Skin Treatment',
    rating: 5,
    text: 'I started my face treatment and felt the difference in just one week. The staff is extremely polite and always punctual. I get benefits far more than what I pay. Highly recommended!',
  },
  {
    id: 'r2',
    name: 'Snehal Deshpande',
    avatar: 'S',
    color: 'from-sage to-gold',
    platform: 'Google',
    condition: 'Pigmentation',
    rating: 5,
    text: 'I am very thankful to Vrushali Mam for giving me a beautiful face and a confident persona. Her treatment genuinely changed my life — my confidence is at an all-time high.',
  },
  {
    id: 'r3',
    name: 'Rahul Patil',
    avatar: 'R',
    color: 'from-crimson to-sage',
    platform: 'Practo',
    condition: 'IBS & Acidity',
    rating: 5,
    text: 'She is friendly, clearly explains the problem and solution. Her medicines gave a lot of relief for my chronic acidity. She patiently listens and gives free, frank advice.',
  },
  {
    id: 'r4',
    name: 'Anita More',
    avatar: 'A',
    color: 'from-gold to-crimson',
    platform: 'Practo',
    condition: 'Piles Treatment',
    rating: 5,
    text: 'Such relief I got during piles treatment. Vrushali\'s approach was completely holistic and non-invasive. No surgery, no fear — just pure Ayurvedic healing and compassionate care.',
  },
  {
    id: 'r5',
    name: 'Meena Joshi',
    avatar: 'M',
    color: 'from-sage to-crimson',
    platform: 'Justdial',
    condition: 'Hair Regain Clinic',
    rating: 5,
    text: 'I needed a wig during chemotherapy. The Hair Regain Clinic team counselled me with such warmth and compassion. They gave me a completely natural look and restored my confidence.',
  },
  {
    id: 'r6',
    name: 'Sunita Tamboli',
    avatar: 'S',
    color: 'from-gold to-sage',
    platform: 'Google',
    condition: 'Allergic Cold & Yoga',
    rating: 5,
    text: 'I had allergic cold ever since I moved to Pune. After treatment it is completely under control. Her yoga therapy sessions for PCOD are genuinely life-changing. Strongly recommend!',
  },
  {
    id: 'r7',
    name: 'Kavita Sharma',
    avatar: 'K',
    color: 'from-crimson to-gold',
    platform: 'Google',
    condition: 'Shirodhara',
    rating: 5,
    text: 'The Shirodhara experience was absolutely divine. I have been suffering from chronic stress and sleeplessness for years — after just 3 sessions I feel completely reborn. Magic of Ayurveda.',
  },
  {
    id: 'r8',
    name: 'Deepa Nair',
    avatar: 'D',
    color: 'from-sage to-gold',
    platform: 'Justdial',
    condition: 'PCOD & Yoga',
    rating: 5,
    text: 'Came with PCOD and hormonal issues. The combination of Panchabhoutik medicines and yoga therapy has made me a completely different person. Regular cycles, better energy, and so much peace.',
  },
]

export const FAQS = [
  {
    q: 'What is Panchabhoutik Chikitsa?',
    a: 'Panchabhoutik Chikitsa is a pioneering branch of Ayurveda developed by Late Vaidya A.V. Datar Shastri. It uses the five basic elements — Earth, Water, Fire, Air, and Space — as the foundation of treatment. It focuses on improving Agni (digestive fire), Prakriti assessment, Naad Pariksha, and treating the root cause with minimum medicines for maximum results.',
  },
  {
    q: 'How do I book a consultation?',
    a: 'You can book through our website form, WhatsApp us directly, or visit the clinic during hours (Mon–Sat, 5:30 PM–8:00 PM) at 501, City Center, Hadapsar, Pune. We will call to confirm your slot within 24 hours of your request.',
  },
  {
    q: 'What types of wigs are available at Hair Regain Clinic?',
    a: 'We offer wigs in natural or synthetic hair with cotton or synthetic bases. Textures include silky, wavy, and various colours. We provide patches for men and women, full wigs, hair extensions, toppers, and specially crafted natural-look wigs for chemotherapy and alopecia patients. All are pocket-friendly and easy to maintain — no surgery or side effects.',
  },
  {
    q: 'Is Shirodhara safe? What does it treat?',
    a: 'Shirodhara is completely safe and deeply soothing. Medicated oil, kashaya, milk or buttermilk is gently poured over the forehead in a continuous stream. It is highly effective for sleeplessness, chronic stress, anxiety, hair loss, headaches, and overall mind-body rejuvenation. Most patients describe it as the most relaxing experience of their lives.',
  },
  {
    q: 'Are Arogya Mantra products purely Ayurvedic?',
    a: 'Yes. All products are handcrafted by Vrushali Maisekar based on 25+ years of clinical experience. They use traditional Ayurvedic formulations — free from harsh chemicals, sulphates, parabens, and synthetic preservatives. Each product is designed for a specific wellness need and tested for efficacy.',
  },
  {
    q: 'Can Ayurveda treat PCOD, infertility and hormonal issues?',
    a: 'Absolutely. Ayurveda addresses hormonal conditions from the root — balancing doshas, improving digestive fire, hormonal harmony through herbs and lifestyle changes, and specialised yoga therapy. Vrushali Maisekar has treated hundreds of patients with PCOD, infertility, irregular menses, and menopause with excellent long-term outcomes.',
  },
]
